server:
  port: 5000

spring:
  application:
    name: Metrics-Consumer

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        hbm2ddl:
          import_files:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:simpleanalyzer}
    username: ${POSTGRES_NAME:postgres}
    password: ${POSTGRES_PASSWORD:123456}
  kafka:
    topics:
      report-topic-name: "report-topic"
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092} #?????? ???????? ????????
      group-id: "report-group"
      trust-packages: "*"
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
